name = "nexus-hello-api"
main = "src/index.ts"
compatibility_date = "2026-03-15"

[vars]
QUOTA_LIMIT_DEFAULT = "50"

[[kv_namespaces]]
binding = "LICENSE_CACHE"
id = "048ccc57edc448a7a69982a6f3c06602"

[durable_objects]
bindings = [
  { name = "QUOTA_COUNTER", class_name = "QuotaCounter" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["QuotaCounter"]
